curl  --request 
    GET 'http://localhost:8080'

###
curl  --request 
    GET 'http://localhost:8080/default/api/v1/'

###
curl  --request 
    GET 'http://localhost:8080/book/api/v1/'

###
curl  --request 
    GET 'http://localhost:8080/book/api/v1/3'

### People
curl  --request 
    GET 'http://localhost:8080/people/api/v1/1'

### Starship
curl  --request 
    GET 'http://localhost:8080/starship/api/v1/2'

### JdbcTemplate

curl  --request 
    GET 'http://localhost:8080/product/api/v1/2'

### List products
curl  --request 
    GET 'http://localhost:8080/product/api/v1/'
